version: "3.5"
services:
  web:
    container_name: rits-frontend
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: vikasraj/awesome_web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/src/app
  #banco de dados
  postgres:
    container_name: postgres-rits
    image: postgres
    environment:
      POSTGRES_DB: "rits_vagas"
      POSTGRES_USER: "rits_vagas"
      POSTGRES_PASSWORD: "rits_vagas"
    volumes:
      - "./docker/postgres/data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
