version: "3.5"
services:
  #banco de dados
  postgres:
    container_name: postgres-rits
    image: postgres
    environment:
      POSTGRES_DB: "rits_vagas"
      POSTGRES_USER: "rits_vagas"
      POSTGRES_PASSWORD: "rits_vagas"
    volumes:
      - "./docker/postgres/data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
