version: "3.5"
services:
  web:
    container_name: rits-frontend
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    image: vikasraj/awesome_web
    ports:
      - "3000:3000"
    volumes:
      - ./web:/usr/src/app
  #banco de dados
  postgres:
    container_name: postgres-rits
    image: postgres
    environment:
      POSTGRES_DB: "rits_vagas"
      POSTGRES_USER: "rits_vagas"
      POSTGRES_PASSWORD: "rits_vagas"
    volumes:
      - "./docker/postgres/data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
  nginx:
    container_name: nginx-backend-api
    image: nginx:1.13
    volumes:
      - "./api:/var/www/html"
      - "./api:/var/www/api-botman"
      - "./docker/nginx/rits-api.conf:/etc/nginx/conf.d/default.conf"
      - "./docker/nginx/log:/var/log/nginx"
    ports:
      - "8000:8000"
      - "8001:8001"
    depends_on:
      - php
  # Application service layer
  php:
    container_name: rits-backend-api
    build:
      context: ./docker/php
    volumes:
      - "./api/:/var/www/html"
      - "./api-botman/:/var/www/api-botman"
    ports:
      - "9000:9000"
    depends_on:
      - postgres
