version: "3.5"
services:
  postgres:
    container_name: rits-vagas
    image: postgres
    environment:
      POSTGRES_DB: "rits_vagas"
      POSTGRES_USER: "rits_vagas"
      POSTGRES_PASSWORD: "rits_vagas"
    volumes:
      - "./data/postgres:/var/lib/postgresql/data"
    ports:
      - "5432:5432"
